FROM public.ecr.aws/docker/library/python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY pyproject.toml .
COPY src ./src
COPY conf ./conf

RUN pip install --no-cache-dir -e .

EXPOSE 8000

CMD ["uvicorn", "financial_forecasting_platform.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
