stages:
  data_ingestion:
    cmd: kedro run --pipeline=data_ingestion
    deps:
      - src/financial_forecasting_platform/pipelines/data_ingestion
      - conf/base/catalog.yml
      - conf/base/parameters_data_ingestion.yml
    outs:
      - data/01_raw/raw_data.parquet
  data_validation:
    cmd: kedro run --pipeline=data_validation
    deps:
      - src/financial_forecasting_platform/pipelines/data_validation
      - data/01_raw/raw_data.parquet
      - conf/base/catalog.yml
      - conf/base/parameters_data_validation.yml
    outs:
      - data/02_validated_raw/validated_raw_data.parquet
  feature_engineering:
    cmd: kedro run --pipeline=feature_engineering
    deps:
      - src/financial_forecasting_platform/features/engineering.py
      - src/financial_forecasting_platform/pipelines/feature_engineering
      - data/02_validated_raw/validated_raw_data.parquet
      - conf/base/catalog.yml
    outs:
      - data/03_feature/lr_features.parquet
      - data/03_feature/xgboost_features.parquet
      - data/03_feature/mlp_features.parquet