from kedro.pipeline import Node, Pipeline
from.nodes import data_validation

def create_pipeline(**kwargs) -> Pipeline:
    return Pipeline(
        [
            Node(
                func=data_validation,
                inputs=[
                    "raw_data",
                    "params:required_columns",
                    "params:column_types",
                    "params:error_messages",
                    "params:row_id",
                    "params:ohlcv_columns",
                    "params:raw_data_start_date",
                    "params:raw_data_end_date",
                    "params:max_gap_days",
                    "params:tickers"
                ],
                outputs="validated_raw_data",
                name="stock_data_validation"
            ),
            Node(
                func=data_validation,
                inputs=[
                    "raw_spy_data",
                    "params:required_columns",
                    "params:column_types",
                    "params:error_messages",
                    "params:row_id",
                    "params:ohlcv_columns",
                    "params:raw_data_start_date",
                    "params:raw_data_end_date",
                    "params:max_gap_days",
                    "params:market_tickers"
                ],
                outputs="validated_spy_data",
                name="spy_data_validation"
            ),
            Node(
                func=data_validation,
                inputs=[
                    "raw_vix_data",
                    "params:required_columns",
                    "params:column_types",
                    "params:error_messages",
                    "params:row_id",
                    "params:ohlcv_columns",
                    "params:raw_data_start_date",
                    "params:raw_data_end_date",
                    "params:max_gap_days",
                    "params:market_tickers"
                ],
                outputs="validated_vix_data",
                name="vix_data_validation"
            )
        ]
    )
